name: build

on: [ pull_request ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules and build projects
        run: pnpm install && pnpm build-all

      - name: Run tests
        run: pnpm test